name: Build and Push Bots

on:
  push:
    branches: [ main ]
    paths:
      - 'bots/**'
      - 'main_cogs.py'
      - 'helper_files/**'
      - 'requirements.txt'
      - '.github/workflows/build.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot:
          - bambi
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Push image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/bioinf-community-discord-bot-${{ matrix.bot }}:latest
          docker build -t $IMAGE_NAME -f bots/${{ matrix.bot }}/Dockerfile .
          docker push $IMAGE_NAME

